branch-defaults:
  master:
    environment: todo-ui-production1
environment-defaults:
  todo-ui-production1:
    branch: null
    repository: null
global:
  application_name: todo-ui
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Node.js running
    on 64bit Amazon Linux/4.8.1
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
